### PR TITLE
faq_gr.md

### PR DESCRIPTION
**Pull request by ICA3DaR5**
This is the Greek translation of [faq.md](https://github.com/rchain/reference/blob/master/faq.md)

Link to the issue: https://github.com/rchain/Members/issues/299

### CODE REVIEW

**Comment by ICA3DaR5** [comment]
This is ready for merging.

**Comment by ICA3DaR5** [comment]
Anyone who wants to merge this? :D

**Comment by ICA3DaR5** [comment]
@dckc Can you merge this? It's done many days ago.

**Comment by dckc** [comment]
@patrick727 @n10n you guys said you'd be responsive to FAQ PRs, didn't you?

@ICA3DaR5 I don't have access to merge this.

**Comment by ICA3DaR5** [comment]
@dckc I see :)

**Comment by n10n** [comment]
@dckc Yes, I agreed. Have you verified the translation? or who has verified it?

**Comment by ICA3DaR5** [comment]
@n10n It's verified by me, @zero-andreou and @thiefinshadows
I also posted it on the Discord channel. It's public so anyone is free to comment on.

**Comment by dckc** [comment]
@n10n the original PR description has a link to the QA process: https://github.com/rchain/bounties/issues/299

**Pull request merged**
