### PR TITLE
Delete Rosette programming doc

### PR DESCRIPTION
**Pull request by Jake-Gillberg**
https://github.com/rchain/bounties/issues/483#issuecomment-372684621

/rchain/reference is being used by the bounty program do decide which documents are worthy of translation.

Since Rosette will mostly be hidden in the background / may not be in the stack long term, this doesn't seem like an appropriate document to have stored in rchain/reference/docs.

https://github.com/rchain/bounties/issues/481
https://github.com/rchain/bounties/issues/479
https://github.com/rchain/bounties/issues/459
https://github.com/rchain/bounties/issues/269

### CODE REVIEW

**Comment by n10n** [comment]
@Jake-Gillberg I don't agree and we would like to add (curate) more meaningful documentation in the reference area. There are too many efforts taking place to move in every direction. We should have one common place for such documents. Our curation process is not perfect and we need to improve upon it. We have some documentation in bounties repo which I personally don't agree with and should be moved to the reference area.

**Comment by Jake-Gillberg** [comment]
@n10n As the curator of this repo, do you believe that all documents in this repo are good targets for bounty translation efforts, including this Rosette document?

**Comment by qelentium** [comment]
@jake-gillberg i think that video's transcriptions are important. So people can understand on they native language and know us better :))))

**Comment by Jake-Gillberg** [comment]
@qelentium, Sure, but personally I would place a lower value on video translations. Written documents tend to have clearer and more concise information that is easier to consume. If there are important things said in a video, my preferred pipeline would be:

1. Blog post summarizing the information (in any language)
2. Translation of that blog post

**Comment by Jake-Gillberg** [comment]
Edited Translation Issue Template to clarify that not everything in rchain/reference is a good target. This is no longer an issue.

**Pull request closed without merging**
